# This workflow will publish jars to maven.scijava.org.
# Currently, it must be triggered manually and uses Java 17.

name: Publish release to SciJava Maven

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: clonedSemicolon/setup-strace@v13
    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Publish package
      run: ./gradlew publish -P toolchain=21 -P release=true
      env:
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
